version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  loki.local:
    container_name: loki.local
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      my_net:
        ipv4_address: 172.20.0.21

  jaeger.local:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger.local
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_DISABLED=true
    ports:
      - '16686:16686'
      - '14268:14268'
    command: [
      "--query.max-clock-skew-adjustment=1s"
    ]
    networks:
      my_net:
        ipv4_address: 172.20.0.20

  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app'
    environment:
      - NODE_ENV=production
      - GNY_NETWORK=localnet
      - GNY_LOKI_HOST=http://loki.local:3100
      - GNY_PUBLIC_IP=172.20.0.3
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db1
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqAkwggSkAgEAAoIBAQD2XwugW7RfQgEy4xD3CNStP7JvvwopbRloefLEEDkH+03KZ7htsU1ol1B+qdwIXppoX0J70UuUSvF7i+47/h5oyFroVme5QJeZ+kcik8lWETfn7dJ8U91Ilv1InI1+c4cHNARlAsdxwV4aoDBcroKmBoCESgDCYAK1DzPlpOImfXe6zrvTjIU3DaRgBMP91NOI8BMXRbuZeFe8f6RwyO7aTWJ+eiFdfwjAm3InNDB6KJhwOfS7W/YGZ4ZrkU9By1K8oywTg+0XQtQIu0ioh06ctuMv7y+pRCdeIE/NPkZ2wQNFPX4JRXKnT/eMPHkhJc7JTJkTblz7sIMMfIpwyl+rAgMBAAECggEBAJw6TQ8U194H5uaz4lAkQ2jRGX+O7wyx6Ai+O9lkSCXtj7in6OV2JxYJzbtkTujnxJYmwevuHjUdCOBFLX7Rd8sOMcde80sf0IKNmIoumN+A76icwHqiW5HqXRasX3UuIRPKQncjOgHCkr/jkIdVCffp65j3rF+VrmHOECSxV877RmpmslHqmeBw2BsV1fhAXT4tCKN2J6ngzA4ecs3LIVulXP5niBJJ0VqZUzo0U84qaVfHqBssf+tUmurcsAmWWbbqgDZN3stfvTR5Wdgp6AYIq6wxc7fNMmZS49/egikntnRWfAHoIhP4KvE/DnW7ps29sONSN2MZTS6MQoCVJXECgYEA/T2HL1p3hp1sCItKxZg7lo2MrJBapb3ueVEKIiaoCevRmoTBB+8K/gBFjTUMdZ6Ue5Hkq2dpLBjzrtmGgQ9vjOFFqLKh4YWpgraP3p0OIbd4OWNwUJuwS515XgoWr+cxIUlhX/SdSl4rEyvf9GLP/PXlk7vp4pKd7NgkNGmorucCgYEA+Q5awFlp4aqBY2FsPCHsC4BCWlbgkcLMAPKL0KTkLG7OOTk65rw3+KNd4PtS+TgdHZtEvb9/2Piykxxc3UM1xQLmNd4Xi3TT/rBEbzjmMe9OWT6V3Hhsp44bZJ5EDCVsxdT/EU1j5EDZ5NLT5wQtaAMNu6YgHTAvso3UYYeYhJ0CgYBszwYJy6Y1uegUV70932YjDxjVgITiWBRiHfbrq45iDOgXq1jBTu17K6S2wodi9ks4OPx2xU0EPIhfpWlMhNRaROTIUlCJ9QNbfZOdg//xbsKCbf5xNCPwqW3fgRg0ZnLOqZfkQddff8ykRSLJ/7b8Kq+E5aXdyz9953TO7GMlGwKBgE8pp+Dhyszm5E+RZNTMN3oEX5LVcHYEQ9G9RoGgF8KjybrYnQdAJk5Kpwle+SWsF10UwEnLt7hgfGpUJpRRy6J+ZGwU1skF7mhS4L21iT2wAehOA1ZblLXBbqWRxLFTp/pN1HFMdwbTMi8QcDhK1J/t8IyHpkeAzHhlqm8BqZHlAoGBAIkYeH/fC5T4oGPWj+vIz64lzvCPz9BHITpsMpGSd2GSQWPc7EcOqmUd/x+fp/2Bw7q63uMD+mmcbVeZVqz3GyE+xVwZLsxLwp0/kIiXBR3RoucTg0agBh6gtijD/pmZr/3aAIOXCClB02nzYtbUreJT5b6KCeDLPCaoqXTrg9Qp"
      - GNY_SECRET=change fire praise liar size soon double tissue image drama ribbon winter,planet wet evil syrup item palm blur walnut dumb tennis deposit wash,seek sibling blood thank broken humble perfect liberty agree summer quick lady,nose wrap trophy tomorrow various field gospel vivid submit live print cube,property response source sand title poverty switch empower seek govern cave clean,anxiety betray ready long protect boy under make taste saddle cart frown,prefer echo woman thank voice submit clog fresh myth direct cool cool,weather broken foot labor bacon finish claw old elegant clip actor tape,memory horse artwork sugar fortune area huge rapid leisure defense waste develop,enlist bachelor exercise soup orient key blood crazy grit hundred hope observe,pond used street evidence aim park quarter net cheap limit tone cart,announce wage session what stay gallery unveil cake oxygen minimum wait comfort,remove vapor course era crowd science depth lazy vapor estate teach cinnamon,measure derive lunar remain ten hazard gallery decorate asset draw price siege,rough canvas expand sail square acquire true afford skull acoustic identify world,violin course jelly humor horror help produce burden ketchup hello rebel whale,pair zero pride boost place beyond wheat blame rely stereo inside you,dream peanut flock employ tomato source narrow sign melt dizzy soda much,room bullet eagle endless run huge satoshi attend swim rocket suspect omit,race capable oil mixture park seek grape hospital excuse fatal essence pudding,board orchard book major analyst crack chest glare actor truth basket minor,critic loyal girl embark thumb guide scheme plunge fetch universe claim bachelor,path squeeze merit music pact female smoke slogan basket task chimney trust,trophy dune bicycle crunch shove net arch toy essay cloud swear garden,minimum fit guide blur truck concert minute brush scheme stairs enlist ready,lawsuit feature air bullet decide select throw worth area huge theory pause,bag program industry execute shine stove fantasy venture undo worth grape ozone,dawn drip fold consider strike process liquid risk trend diagram smoke machine,theory senior finger olympic purchase spoil decrease alcohol doctor gauge guess wedding,mixture horse gorilla main adult spy pact crew drop mesh inmate film,nuclear wealth divide yard extend oak bright cupboard blue master pupil live,disorder client bamboo glue mask hub benefit lemon cupboard obey tail battle,success mansion search indoor clean morning cost weekend exist youth silly flock,art name ridge hint basket erosion client force crazy track view fragile,hazard brother script pool snake upset rookie helmet casual ridge prefer retreat,sphere smoke enemy issue deal holiday trash unit stadium turn soon bounce,antique feel common banana gentle industry present industry skin carbon canvas door,much upper creek ship develop twenty shoot fine load world nation oyster,mouse scan express arrive drama garbage milk hire depth clay genuine volcano,ripple salt defense walnut chaos kind girl travel pelican sail move hero,hurdle sell airport lonely earn fold practice adapt enjoy flee promote find,assist lift cycle table quote wonder grief clever genius surround tonight jacket,fatigue across name couch stick bring achieve year damage curtain square inside,hello urban risk stick animal lazy simple nurse smile divert junior resist,voice web sentence math dolphin river present someone charge syrup vacuum captain,galaxy license please flip result soon shallow damp hungry calm session divorce,upon legal embrace upon divorce write slot surround celery lumber maid cost,trophy marriage license case prevent actual never earth common alien tired payment,skirt zone hole orient gravity unfold ritual deliver furnace mutual grass group,purity decorate dirt stereo festival churn arena kiss merit fire culture fruit
    ports:
      - '4096:4096'
      - '4097:4097'
    depends_on:
      - loki.local
      - jaeger.local
      - db1
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app'
    environment:
      - NODE_ENV=production
      - GNY_NETWORK=localnet
      - GNY_LOKI_HOST=http://loki.local:3100
      - GNY_PUBLIC_IP=172.20.0.5
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmUhjJ2EF76PVcRxWcijf336T6cwYnXsrtqQ3nEy5jeAM8
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db2
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQDc0BVL82Vbm8uIpydTj7gaiNtTm4NgHmZQrdVLAell24KbBVR12QTlwyZf1CK8hkRv1hT6TYyHOW3vGJe3wUqFVoVY5kgl6Uz5S0cDWOQ+4EIFkzsNtf8WPqneUqTQ+x6nmLVRr5ql7vVBG9r3VPE1kkApSvTknSJ8PjFM20gciw3NCG4dmPH8sKWLNF7mxy2J9XvaDuMzd2Vz8LmHHlJfDaEJ0xkVUMdnOnA9PW/liK9m0HZuK+44EXQi2V1e4uAP2TJJM3jTbTYr7Nj6mH/lfVKJ4aAFo5Ls7x0RzdVXA3DLYg3bGop78d19ILpxxgfP7ZMl7g0lYmevzRRXX9KtAgMBAAECggEBALsaZrFQsJYLUU+ds6kOosV5Kb+SiqOrnq7GXXGNUSPJ+MU6ovKozYmS7rVMn5J3gw3wrR3bEDSU6R4sDILb+jU5tww5NPFK2rpymt2vONg+VjM7KlLX4CoNNwr3pEigQL1qnFl3Hudzr8VXwRbKlwj5v/w9U31T2KDGYifptxTW+yxeK3tiCSXt3ltIPnWA2J9mO0gvtTa8sh3auJwHp86aS7LnhRgPvNDPiX1TdV6e58/1QE0prN2YMZLS0ey5gb7N3cJ9/K7vxsDgeg3ZTEDqSgDmu0109b/OeiWAXAXGez4JYoJr063mpuQPQlMoLjNi9agSOn6+puKlfY4XogECgYEA/iU/FiMBhryg18wKxS11iwyh4eEYWSAijrF+16wlN6nO0s988OhVAGrOGzb4LhK6UtX8T/yZzIcebsczo2LrZQCn+O5SUX6n1NFjlNIXbWZvbxc8B8kOAQN7qGR2p+zhjIp6dqTLTQyIRwd99UDDXJmEFjsH4eMh80emynfivCECgYEA3myR7sXF2RP1TeqmaV3cT5CHF20HJa2I6LVLHEKRFghFKB3QUhwbc+45Dw9R8yGUaZbosODwLwuFU4dnOwJ/Pd/lXCrv6MdtfQKn03F98jwf2pT/MVwrown6UMsXQgn1CpGvxVS+LsSAYC26o4vL6isHgyxS+HPeN+GhHYI7pQ0CgYAjyQLVDyDL5AuR1z08/mWqqqCwuY1AH3I+PWfq3mZvLA3fSTACi/RMFr3mvxq7AhASUecxLBRL5Eq4tnvi6a7TjgAY4RXeO8NOCB3Jerupv964+cCOKBU8t0zWLS83/fbUXztXMWUe+EDIH5nwyqm3hDZBGxbFC8JgCxrFL5RRgQKBgQCQZ+KzJ/oUvs1zgdX68LJZgdcDUYjjYHBTzWhvd5RkvofPzNN0i8UTFmY7LdIhzPpjN1PpipDFqnAsU+uktzFPRa7OkR3jfp7KG9BEChogDAMOUdABBvtZxd+bVs/J01chPobk0ekLyg4i422aQufoJ3mgI0XXArsSgs2sr+HzfQKBgQCMgkdsiGR6J3F2taJnUeMp+w4zV/md1mtrd/zdhaeWJVjpn+lX6Dn0PzJziSbMzzSRwLkVmrDwyhmwgSRkFNKI6O6JbQJ7W3/JHi2a4t5/od9+mmuH98sz7P10frczqfApLl0cahMfNi0NFeRvXHxVnZFCpc1aQl2eAnhAbjm0bQ=="
      - GNY_SECRET=recycle state immense shiver skill tomorrow wait verify crack suspect hair hurt,foam cute slight work jealous animal since record way dice stay private,vague balance panda alter kitten power hawk extend jeans aware pony prosper,situate spread maple mango picture cage rubber foster perfect sport taxi circle,air estate slush other carry once walnut evolve pioneer glad immense forward,fresh stereo wage intact horror diary head garage marble sign garden twice,tube vital sail then shallow elevator quantum boil collect ill place apart,balance width aunt ethics jelly rude trend organ protect refuse ability engage,galaxy food remind fortune food pistol phone urban next glide mushroom artwork,whale wasp inject alpha jealous protect legend attend wagon summer screen purse,aim various series struggle wrestle equal able chair usage source front lawsuit,nuclear begin place deer orbit bird nerve miss forum drive exhaust run,limb chronic crazy fly identify current minimum creek tackle that chuckle august,menu relief skin gorilla feed bulb result pudding audit mimic couple stereo,upon tortoise attract shove real chat near escape drip tomorrow company nut,model flavor display wrong denial access detect clog wrong lawsuit cattle minimum,desert spoon dog wisdom drum shine blind similar hamster kick shuffle opera,rain finger differ fabric paddle guilt popular theory skill grape satoshi motor,disease kidney stay scrap process educate link fragile boat dragon away pink,carbon mother village favorite unit actor protect useful debate super loyal hunt,turtle finger knock teach dignity phrase glow angle mutual grab jelly dress,ball begin direct film topple bag city primary model federal apple blame,latin orbit alarm boss plunge negative inform side urban wear child sun,ordinary toast bottom comfort since crush half used reject route drama tooth,head bright media loud sadness weapon liberty praise country viable poet vendor,best patrol report hello upon snap piece tattoo emotion avoid cushion clinic,album sun hub cloud happy stand kingdom abandon identify voice welcome clown,share reveal lady lamp error jacket satoshi skin maze thrive saddle toddler,sadness stool infant candy mad curtain guitar elephant web tube equip desert,conduct print infant company convince opera auto awkward matrix true lend ice,must pilot visual hospital adult escape spy usual coconut amused calm race,winner tribe album desk often october diesel sword inmate slab hospital slot,horror feel carbon bag alter cruise noise aerobic ecology inhale debris name,island blame visit much excite churn beauty vault skull inquiry toward blind,display tackle neglect grass angry miss general expect badge all oven whisper,smoke dad goat wash liberty close guard dance actor legal wedding addict,stuff rough secret dinosaur property absorb unusual rally boy quality train ask,domain harvest stereo chuckle shadow lemon window text street amateur street leave,blame blouse ugly news sell sphere steak comic weird borrow camp crumble,upon amazing soap message summer achieve nest wreck follow stomach seek merge,polar enforce reform squeeze gate picture old swamp nurse stone crouch exit,combine build panel grid mammal tourist screen logic sing bus hold monkey,swallow split olive detect crawl energy number auction excite such tray yellow,print island solid banana merit domain payment purpose garbage forget about travel,tail dog coral mountain evidence cool army small walnut accuse worth ordinary,polar brave stage injury stairs gravity ranch thank hint engage ask gesture,lab evil orient rabbit crucial relax orphan assist marriage dust south meat,drink analyst design poverty traffic coyote mind window gadget plastic beach ill,loan feature topple dismiss kiwi wonder screen scan morning quick rough grit,census make riot edit rib plug hungry lift hockey system push regret,grab prize sphere pact video submit cook heavy burden faint belt memory
    ports:
      - '4098:4096'
      - '4099:4097'
    depends_on:
      - loki.local
      - jaeger.local
      - db2
    networks:
      my_net:
        ipv4_address: 172.20.0.5
