version: '3.3'
services:
  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/should-connect/node1.json" --publicIP $$(./getIP.sh node1) --ormConfig "config/e2e/should-connect/ormconfig.node1.json"'
    environment:
      - NODE_ENV=production
    ports:
      - '4096:4096'
      - '4097:4097'
    depends_on:
      - db1

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/should-connect/node2.json" --publicIP $$(./getIP.sh node2) --ormConfig "config/e2e/should-connect/ormconfig.node2.json" --peers "/ip4/$$(./getIP.sh node1)/tcp/4097/ipfs/QmUhjJ2EF76PVcRxWcijf336T6cwYnXsrtqQ3nEy5jeAM8"'
    environment:
      - NODE_ENV=production
    ports:
      - '4098:4096'
      - '4099:4097'
    depends_on:
      - db2
