declare const _default: {
    maxAmount: number;
    maxPayloadLength: number;
    blockHeaderLength: number;
    addressLength: number;
    maxAddressesLength: number;
    maxClientConnections: number;
    numberLength: number;
    feeStartVolume: number;
    feeStart: number;
    maxRequests: number;
    requestLength: number;
    signatureLength: number;
    maxSignaturesLength: number;
    maxConfirmations: number;
    confirmationLength: number;
    fixedPoint: number;
    totalAmount: number;
    maxTxsPerBlock: number;
    interval: number;
};
export = _default;
