version: '3.3'
services:
  db:
    image: "postgres:9.6.12"
    container_name: 'postgres_3000'
    restart: always
    ports:
      - '3000:5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  app:
    build: ../..
    image: gny-experiment:integration # tags
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; node packages/main/dist/src/app --ormConfig "ormconfig.integration.json"'
    environment:
      - NODE_ENV="production"
      - EXCHANGE_API=true
    ports:
      - '4096:4096'
      - '4097:4097'
