version: '3.3'
services:
  postgres:
    image: "postgres:9.6.12"
    container_name: 'postgres_${POSTGRES_PORT}'
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  redis:
    image: "redis:4-alpine3.9"
    container_name: 'redis_${REDIS_PORT}'
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
