version: '3.5'
services:
  db:
    image: "postgres:9.6.12"
    container_name: 'postgres_3000'
    restart: always
    ports:
      - '3000:5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  app:
    build: .
    image: gny-experiment:integration # tags
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd dist && node app.js --ormConfig "ormconfig.integration.json"'
    environment:
      NODE_ENV: production
    ports:
      - '4096:4096'

# volumes:
#   - .:/home/app/appDir
#   - /home/app/appDir/node_modules