version: '3.3'
services:
  db:
    image: "postgres:9.6.12"
    container_name: 'postgres_smartdb_3456'
    restart: always
    ports:
      - '3456:5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
