version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:
  loki.local:
    container_name: loki.local
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      my_net:
        ipv4_address: 172.20.0.21

  jaeger.local:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger.local
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_DISABLED=true
    ports:
      - '16686:16686'
      - '14268:14268'
    command: [
      "--query.max-clock-skew-adjustment=1s"
    ]
    networks:
      my_net:
        ipv4_address: 172.20.0.20

  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/double-spend-attack/node1.json"'
    environment:
      - NODE_ENV=production
      - GNY_LOKI_HOST=http://loki.local:3100
      - GNY_PUBLIC_IP=172.20.0.3
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db1
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQDMmy4HlidPKoQmxLf8u5OTuj1xEe4CG80mCAWt0fMSFzkX5iEqMSKr9zzUAsB2FPF+lhk0Mn+h1YYFL770hk1tiEq6RaJCXI48UnGfJi284BKfN9p6v/Dh7+Q7wgBnppcDUr/NJZewH77mVheJS/x8KIxrYtxNmZEzTq6ICBiaYEGmk2ihkB33yyaUzTDlDddzZK4YXvoYxNC9+ZIpqMFvsSMdeX0qIjxybGlJQ3BC5LLI+b0i5P5nbOI42RYPPi09M6hkMf0LdUjxmNPCuS+YLcuSNcL6BAIxVMHaJe1nFAad8jDl5dgDrM+sAGmIRc1gqbYltl06GhFpJMVkZrwrAgMBAAECggEBALuQ+pZr2Sdi03jy17PxhS1lCxRPmoAGWn+l1Qbus8T+0xEMn5SdLKq24OV+jE7zjhs8oGhQbt697rlsdsKVJ//kdJTkZwYs8RttfMmn50ABrjCVtEzZDoshLnp1s4dRmZirUDdRYghMYeWoQLVVmmV7ipabL1hYElsVozwDKALD3RFWqeMfUFR1d687hFigVhlaESl/qWQmiOC7OVQ3fU+u79ODa9jh9CdY97PZ2+x61RxCIEI7oE/fqfmxErf1U1PBgJ8UsiJva8GzyqpeuHiTU9RstWp3mldmctrBqlHo4ufP11vA2L+SPwJmNLjZ0IzF9txm3+9awqySMJbTUwECgYEA7owLwfjqsderZWbtetNXpvNII0v0pPTgt/LjEsuwvh+LVIP2pMjI5YXz1pNIgn5NliHiDxWbgX8GuZtS1XdJ8pG8HbTtim57ps2PIAL6WCT2QBNnnb56gJ5NfF5sOMMOQouRLH5lUNaJfLWKOUYczH4KAF/hQgsZjmeAKUCjiqsCgYEA25Ns+/7ws1U9LTTu/1ZiW814YxZZhe8x4MfU/fcmeSbfwMq6wd0R0UuzaNetsZ8mQEZV75xphBXnKaupkyFOAiexzBs9voCFjYeOifxXHqE3R2v4FnNBLx5dp5w8LLGKvuifJ8xhttWew6+tFDQSIfYZVb56nwhRMdlTUjF5lIECgYEA3ZEmupxBIb54bE8V9SeoGmGNd3ttWGo676CiWSroly8lcvK/fH8iWk35FiznBI3b8r62AdzH+5fI30ztu2h5Pt0uJUmP+Sx1nZEAh3M8o/Jw50Me0t3BWwWuYv4w9uf1rsmDphggct1SBot4P4pn5WiMUZy81WMJ8cMgvzBSttECgYAJ1V1hH7a54UxfFOrLJpw7DkWg8mRJ+j9amLhyMzpW3KXSpYGdov/kRqafQGF3/e+hm0TH+VJEZxK2LAjpHOm4cPymbmXifTD9+J8qkNF5/rBSE4TFxJ2btZluIzISslTLXfGav610mbaFfv2aVQam3LWfwGsPajjwqZHwsWSHgQKBgQCqKks8gyo4zoJie3LhcDeygPzKEesk4sIBEjplEpD5uolHdkqQ4+mRBr34yIbx3ieHvwQ5uqqFe0hqHrsxP2a+JzZYxhUQBe0M23gPPzYZSw+9KdC68s6UGeY23H7vSiRBTP7+vTtPGSETCfAOnj7BVnaP71soDJUmqmv5lJV0KQ=="
    ports:
      - '4096:4096'
      - '4097:4097'
    depends_on:
      - loki.local
      - jaeger.local
      - db1
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/double-spend-attack/node2.json"'
    environment:
      - NODE_ENV=production
      - GNY_LOKI_HOST=http://loki.local:3100
      - GNY_PUBLIC_IP=172.20.0.5
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmQbVdde9AeXSP3FoLyVNd3Fi3BjCe2tFyJV43bNWEBYSA
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db2
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQDo9QnqRUmrO3uAqyoAAnjmDB7+lCSA9a7tAKv0vsq0fnq0/espA70e7sJZSjmHqOpP5Jyse3pjezMfSsBR80vQJheb0dOwCsZu/dJ2kA0nuXRZwOd7ZUUsRUh5oj5NFBrY3tuScq/HtbXDqMs0MZdlKIBkEseTnF1rLZw8fhIiY3AFwlJFUCNGKyrk2rk6IvrwMWshyBkr+r1pPfGp6W46/fw5gwdvRTgxCvmqkQq35uncosBbV2+lAimvviTfT7NR6SuLdkAb5TqC0kh7XJV2eu44TtHwI/rTQw0lfCg/WnRKA+uFyedeg3BcTzqjdnhkxP8v7KAMnxi8Z/3q50jbAgMBAAECggEBAIdelQNoffWd3BeZ3w8gYKa1lnEzHr89hQe94y6Wi+40rRNtlfBAdu55qb//LM0TMA16+DwWiLk0RzHA218DtSNgb0mhtZRPvp2Sq3EwJiTWVLEvMpR29apTHFlqGS/rJequHgPM1y6C/fuTo3lR8/rZfTop24WAUJzOZUKVs+38pJzwQYZ1+BNU3Pbi5YrImpSvagxWMZ7Gfj8dKTbFSNwWxY0wjvaCRJ2l5QtFuq5+7vstEnl6lovSa7HR+L8kZRkjGcdgDG9PUXZfLHWXGTfml657DmRdZVbt/qvLNfXyBOQLMHWj2QBOkMcEJSC2AlHfFbodlMZzKPeDhSn9bCECgYEA+mZTf0y6ax98eX5PStoRAAELbcJ78qFhodppvl9oNkbVju4JyWxTweMCKl5UwWh5PP2qxdTHTGeVd+t3uvcGkCY5BpmbSvX940ML+M/U1JjkGnHFEX3YcbHaVgzjiW3seK7vo8gRvFb4f0diFb4vNoS+O0Tc7rVyZYQ/H4F/ZosCgYEA7irYOy4K+Gm1nxx7F+rBDnCfutaG2v97cweAm6xV8ZxNQNrZjLGk1CPXu7w1QVs/ocrIGxIUvtrszUWsEbETXX7JO2MH3qBc5/xryq/ozW+fZOLk2DaTqprLqU9zJV/fUBUuE5XCxXab8r6zpE06mWsosdq7KY19dsoTBGifQPECgYEAtyWnBuJZK8cw5TBE0OvlKUqaUGLDA/mUDq1RUMQ51hFDXLKxB9mq/ZKL3+91MK24l6q2gNKcHz9YbQkWXvMVotPCPBiYJGD+nX5JwGhLNGDL3qe+S4fvi2FZ4Dy3JKr5HmBduT658jbutTHCBUNBBzBab8Fzk0m17ZioDuRKCfcCgYABe5LNC4RV95KB4xOBGp0JEfpsl1lPk7eZB7rtPS1ry6VPeg1Qqupzx6VYLdvHBGJpB3IneP1YEtTWklB367pLIrbt/7fU0vrBFvk00dOJM+CyKBd0oSJaNYx/CVeWK/qf7QHUbWJBCHQAFt/XbgOnYNtoAAyaPZ9CVg+4P05+gQKBgQCw9Dj3nFZxLWHIFK2y/QxFhw06mUYck8SzS2hbDhoLNUlVZz/kSIywb4Pzj2d9dr/QA6gCVZgcJ00NgCkXCWKtYtbSPK8ppv8/+ILVJgqS8H4PEnyn3C/ewPisaAPTY6V8ijwcUB8wJFXKMzkpUllxhHjRaBz5kkE3br8dOulmLg=="
    ports:
      - '4098:4096'
      - '4099:4097'
    depends_on:
      - loki.local
      - jaeger.local
      - db2
    networks:
      my_net:
        ipv4_address: 172.20.0.5
