version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  jaeger:
    image: "jaegertracing/all-in-one:1.21"
    container_name: 'jaeger'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - '16686:16686'
      - '14268:14268'
    networks:
      my_net:
        ipv4_address: 172.20.0.20

  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node1.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.3
      - GNY_TRACER_HOST=172.20.0.20
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db1
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASpwkwggSjAgEAAoIBAQCzaQl106VNz4h3jxZVxkJl+3Oh+KuXKlLtLm7mQL9Fntm5LhLTowaPDKCWbOI4MyDUa7epOlKlpM4nyJ8JQ0anmedYsNdCT8vqadDW1VWYkvWf5MaWFZJ1hRdy+1Ze/pK9ILgT9qFcBfw9XVIp0J3miUtCG1CvvbS7xkwPiRtd2bxIjGcXcWYhHNY0apao2GwCog8nsukPDzUYdjiKfEFgDsNBAuav9JP9Bh6Iej8H/zJL51UpcYCrgUexftoEsojgaaQex2NjDq5Rgroa02j/2FGlQ6MZBTHYbr6xLIIqdsXzNI5WZ+u6EvmOavaMkkUxDDX74qMRTBgbI8/RVTX9AgMBAAECgf84EJrkNz9xEWmT8yMHqu0U8X8xHoSAuLkxZVFCovkiyIFBXSSE/m0ORuPoHh6TcWbQ+thqCc/J87Z4uDj6rAtoVK/3B0w9bLJMjsS0XfZht4sKbHOicxtRnkW1qNVU2jkA4TilBG1oVHZ+tqr2Zjrxz/W0stSEFsRj6ZPbRv1GVj3CgvFW1SQLC22a1VMTdCARBgZnf7v+uJt5UFvqjn51VnEuJZoCpY5baSEgsE5Y61V/fqJmpfwpVB/4L3KKI251YagZCEDah7saJOMsAKi7YmijT3mPAXWq767wBYSBeIw1NSmc+efVFUBz8C8UfnSRCACHJ6oaBrFUhmhsQMECgYEA7wL6kpvhcEgzYj/0PwR8TlgmLgubS8dLsFix9MS4EIiUlbtyRv9M6U2yVILLvx0Bf71MU08sBx/4HaaBgOsYMImTX4gpVWml+n4ujiPKUNvd9hdBPcM0MTHO76cnaCMkGbf9c2wxSAMqe1ak2TcWlS2Xe0R+kW5r7xYtAxffE/sCgYEAwCmPlPXhn9hRi3oGkYhFEmbOyVc3K7MbMOzRmW+i4Ms3S91HuMl12qw71Rl2tjPet58nYi/EPVqIP30yafrtozqisw4DVL1NO2btzidjPDCjgeIboo3g8bIoSQr22FdcGg8yuEnE+rolBhpdrUaDkwUZT1OwQNCqaxREcBdYxGcCgYEAxK9T2k/yvb58om50pWMglCwQBzY/7qUrkQv8LauwuNJcS7d8PBadiSQKC2ezGStab28snyX42kghmuzJh3hvaIneP/BB62rMTo2F7Cxhshas2nWal6PKkG0nmKmaUSUR8SQqqtAu4c7RJ7xOXf3qVIq3LJZZ/X27zn0WP4Rma/8CgYEAvI2LV4zUsPWfPg6kN1TRAbdjHGi5t+VsvtsA51+FILIGNiiQYZ88Ry9NHlJ4C1xmIyLFkDByjAkzO6jrONaBKvM0BiGv3wxIpgrfOLOpSbwoFB/7Icu5dy9rHBDoGWvO8bsL94xa/fJ8tbpVRNq17CLKrO3fOhoFvkAKzzn5Xe0CgYEAr3VFe9I3zpBaPgc8R6NTFm/9H5BB/PljstzBKF4ECDtQ+ZfngjLNMi0+9HK1SLcWUhW0uBffBT2j00dVGacX02hh9TodkmGq77rZWpqlynhTxbn8I9WaYDhurfWXrONc+LDnbeqIRGPPSAOQm7DH2yci8Wzj+BPOwxct6+M7/bQ="
    ports:
      - '4096:4096'
      - '4097:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node2.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.5
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmNurLAfquUV58wu5JqfVk6DnRACpkzaurNzm9WK4ARfYd
      - GNY_TRACER_HOST=172.20.0.20
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db2
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQC3H9azHRSZH5wn3xZC7Dx1uoHbRQAgltB4PLhvBWuHb37932eOX24TojPyn3ebMoKdhXKUGP3AJpSNc+V2v2mNyIs6pfsPGU4LXJtclwCb9rchODN3PApeSsDOuIpuIxZcae5g6Zg3k5UIeuZU5cUo2+b3AjqfP5MyvHS6Q8eqM39wcFuy/Nrr01QiAQO3BAYNw9YczAhMBfVhNydXsnYIt2UfVxAHYjpBe3zuBNkd67DcnS45J+oCjCB0fmM2R1zAzXwKWriPcRJS/Ms/lCQj1GQ5s4HQ561HDfzpqhUJMLcO/8o+UceJgFSJFgciD2yfr2HnKGxw9aWKFMWmdQJtAgMBAAECggEBALDDDt89xtA3bugdssNOfN229fnNlN3gNcKZ+f1QYgcNXKt5peALxZk2DKa5vx4Tl3itg3fo16dOlj4kDO6evSia16n45Wohpu/YqC6ro27oqsRqF2OUlP2Hcq0X/KdrPv5dUjhBwyiCUG0rFIIGeFWETmFHyYZGO7PRrWrOWkCyaHb2ZAYEw2ZFAfDU9R88QoG5LhsrlVGPBRif4KjB5VzfB9dewbNg3DlQqSmMHzv4Wbk3GXkAksWBAI1zLnY9PQwjwzMEIeXXDcKnjvvMdypbTzcaRXVL72hEY53fowMZiyyLbrj2j5v4ZUuApyHL9WA1h/RIsBTZ/DxamALkpQECgYEA8S09FQF/f1Z1x64GXhtorU1pVPwzQGh2sFM1EL1cOwaRTH2X2O7iKeMiWsoM620CWWh0bcD3YTlpoCyaNSYzNCNGHNsNeF7S/heek3sj2KQSWfcgJWoxaRI9GJX2DQc6p+Hbpu/8qMmP8R/VG5rqfjRWoVfXxpQABJCDhc3s+FECgYEAwmEu/ZtLPI579qZLErE+VARGsSc6CQ3GPy4iv7EBNPm+/04to8SG7czWkuhUazS5qd9Y5dQ82onkdqwCkEfgimmhJPsNY4CYLB4D73Y9nfo4VFrqRH6ZPXBzSDFO/MdkzXr5hSO9JxeTiJwSysmcyNDcXo4t6KUnaocpRxubvV0CgYEAlBOAg1suGtLM8dKpWjJd7LmwyFsoZI0/Aje0RxjcfekkYOBj0O+qsKkiOLgBgrKlVJvLkG9/85O6hHueGq/flE1sCN99v8AIr7V0yXw7oBHsqowOkqpGuApYtLWuIoWjv9vubuq+KCvJUvSGdbKB8wbTgbBbbTMFZ8gK2KZ8rmECgYAqdSXZeVE+wfSr1HjzdUmi+mgii+nuTlbuN/qZGmWkF6UziPUJH4VFbge0gRDnddXUGBgH44sDRTlk/n902m5ebWIofLnY8R7MDCZZ6N7eoegp7M3c9jYsqGJV84dISZloFKNqBHttjYXJQiYMq2sWpiBseuvmNCTe7PUENjCXdQKBgQCDxMv0IFcRNcvnIXiEgGAgkC5cHJBYnKpwYMfuecteKVjTfkNlZR1+bzQNICbikSEzrqEiLd+KzTK64yuJXrHybSuTbT3CywY2ptyBDtCbKZbC0pn7N5ZjnuXtsb/g3bgMVLooowbzG+vauhClBUqgT49s8hyxxgN3MP84J45bvg=="
    ports:
      - '4098:4096'
      - '4099:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.5

  db3:
    image: "postgres:9.6.12"
    container_name: 'db3'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.6
  node3:
    build: ../../..
    container_name: 'node3'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node3.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.7
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmNurLAfquUV58wu5JqfVk6DnRACpkzaurNzm9WK4ARfYd
      - GNY_TRACER_HOST=172.20.0.20
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db3
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQDtFQJ+vQBN44+m6EX9MWTJfqYGlMWJdlV6zWrz5ZrPIGk02ilEIV5oIPr/jzDfsVkRtJPqY/qgBZ1X8FyI4Y1tS47SG4VxY6UMdw6A5oLWdigUfBoYQpuW5+Py4pDIRuZKmby2U0i2CaCy6d6f5v01Id/wNX68yTw4t7R+jdYqTXp/1ToaPp/PjBzR5dZbaKKVT2SxU2LMhXGTmBWlNjZJipNy8fGSOLcH3pSBQMcU4IhWGzKFBfZ2Ezgj7HlOAxsF0CwLVH3m5jdv3nXGiA7lPZCi4y0+DDCgP5nMKtEF9wgnPNOqKIu2EqFIMoWr8YQvfSql8BB8ChOrb8FkpVo9AgMBAAECggEBAJK3VsTx17db5TFIOs/WemXLj5kxBhHsfjex2cc3xxb5GsJPZAw6jj7ocgwnI/q6uMEhPAxodNgEwXuDTvCSjMAfazIRQAKMxL4zC3GvtTZdBq6uokNzLPA1bzaHCUw3vBpci5FVdwDYcm9mFZRlETuJTBlOMbFI45DB9tv+kJO6D9X4O4W//DvkAYwpSll3w+aYNi1CQot8oLegJUN+E+az7KayS3JQCPUcDk/1XoQDPlulzIatmVff7Q86lw5syTznYFV8yvUAcL/c1bNyYd1yvhuya7lvxD8831361pYQ/VjMndlg3tGen1VZzVEznS6+m7kJLUIHk6wLb9Vn34ECgYEA/R9a2HgpkVNtLPaapDBtgPbeHKkQuT77adnSSiSTj+EMRnF/17nBZnc5DNf7zhN+OYSlgb1JlaZcgG+04TpQsf1s9MUfuNNTfvYH3XdHpU8vHleX+7ekD2Nw9lUSnt7hTdvVTF14tG0YnqfDAwnL1QocbWeS7iTZqdBFA8PJ2aECgYEA78b5O41k77UzHsrYbRLv/PZWfOl/rsMQkkZWdnY33Z1/SIOJ29tcO+xsrJSjHV31d0eLqw71+doGqSqNaV+jioU7FQG2cv7CdetQRrE6QZTD0j3btNfKu7N0fdb2IdlfeCuXdWLGUswWvkXpsIDgZM5cTIL9WJq8aVqBtA9o0x0CgYEAmt2xNlomjIyvcmAa8zPR+6KO+JgT7FL1fajQeZ5xTglR+lN89V7oTinJlOscW9QfWU+n9335ZH8Zf1dZIqgMMSotnIByzSE2p6od28kb469T08uh6FdOIEAmIACi2OLilEFY+lUCAdnxwzg/Hz/CH0EFbYZ+JggTyErtvsTuXaECgYAMP8nztOF3LXaTGCG+UL1Z2uvILdWMBAMQte8s1hU8iRM7jRy50pb/qLBUkLNUiLxFf64u6vC99tloQvg+bdhY9z1xcUj0zvb4NzE+q0cimor2bpqOvodo114YH6crS4OJDBEMuiMPj8WJquCpV6we+jvU3Mw8fosphqohnLfqMQKBgQCy4VSN9vKigKZ4N2j5eK3/5KKLtxnIm8D6OwLeVc3vKoPuNRHFsK/EO6ejVBKcQSG+ztUG6iUgWiVMvs1f+3yIpAFWozOMZ8XQPuFjPMRSuZxCqWYFXWoa6mDxrtYXxFd0Neag29yMa48O6gxlhDzO0xtGGw14QJrlJK3VyS93vQ=="
    ports:
      - '4100:4096'
      - '4101:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.7

  db4:
    image: "postgres:9.6.12"
    container_name: 'db4'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.8
  node4:
    build: ../../..
    container_name: 'node4'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node4.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.9
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmNurLAfquUV58wu5JqfVk6DnRACpkzaurNzm9WK4ARfYd
      - GNY_TRACER_HOST=172.20.0.20
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db4
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASpwkwggSjAgEAAoIBAQCw6ys0Fmx6NdDYS9HKo8tu7wRM2/MoPkyP8WxrFk3USd1OPeAL75b8JXwm50LhVh9BGEnEahsNcWjExRWNzwriKdlleREfipyaRQEOqsdONycsIWnUOBbyxR4qsjiR9gUYUOJX3VJfrQK10M4CDnmXOMDRalcZx9Y7lbkgllTFq0w0xi7tacdxnCOzSGp4uSfLmojY4Pgsufa3cIl2BEBBEjurJe8ID50AcyDD3SkWmvLoBHlVSWcEZk9eWi1tEYR9L/x49Y6c7bly1ohEyjtxwLRK0YTdRowx8/aMJNGN1hKJZk7SyNcPrHvgWo5ACXCkisTD4o+QT+UZLLwMlodpAgMBAAECggEAZLl/H2ik2e9Jt9ty1avrZn0uNZQEHCVb8ZfB4jYQmYx0MteHd0Qw8d1lkcCYkzI1GRp65RiDzmODAoQygUofKCQrYVpMJWkFP8+JipAwaJd99eIQHoLQjecsBaLyEie/PtjOBLg87bvSjzESGJmlIDNvk8q3TDY6AjJ789Gi8eZiXGrL581JUmzXHkMZ4xadk9f5uZyxs1bePJxQU1OwM1KoyAbsBMmNWgEsmu/+7hrOIuubNGjew2OVCx2ZXuMjhLsYVZCARNd0fI3KVN+C94GAFJ/vTTY02kDQdCwH2nxZEV4Q/qrLn6nvS08l0YkU8AjwGTTSh+PF1ApwEOQnAQKBgQDZDIyTKpkhysnQq4uBurorIP85LkiVS+7ek153XqEbMm8BzvGOaxLbtvwTBa3Wf/JMhW2N3fjpWL2fULbQ+VmjsUiVu8JvuRj3MVledVbQeN7BS6XhWjhbpfMLmxnrj5H9Ph0P3MCr6M4Kg32s1X5fGNqWU6nZUQfKm3ItYfm4mwKBgQDQqv0sif9Lars0p9UdLFGI48MtS5gWzWnuSr/eY4uEvBDPabWOo6U/gZI7qAiA7Wz1AEWymfna5ZroYLigibKXoYocal4A4lnatWXX5f9Ua3WMF/re676yaPIiWEHQbqYW9Ne4ZZggGjTYMBWgpJ9xUYVeER7xjKGWYDJn1mJ2SwKBgEXaiBOFDiuV/EWwMAHcerYOtJVOlAWYnpP7kdeRGQCLxrYqSAux4ivcRFxK45u5Kd3+wzd5TPasnLp9W5j95x+LmvS1rOoQBDzqIP0Jfpsxi19iXUydoK2+Ru5hSIJLfoymROwp+8hX8JfpobTSMQ2iDhd7bZqHPZ6zUJfShHApAoGAclILjJg6DtZ1o96DSo1aSjYGW018EJoPfCblwXAmIt1qFEhk2LXdNdLGC/r+Vaw+MmgoxzXGhl+eo8tBu2pVNu+gm/rGb5OTCNiy6DqwzU5mQw9sOS9M9a+7YIeb3xaP1inj+blnQ8c3xm1pm+41ED9KYwPcQRf7+0fOtcblgMsCgYEArvcsrlTam7McDSsJ8vjf8PGCIELLsUA40AlAVXDdI4vhCbA1XWpuMNGM2h+ksia9kXXKMHqKWYubdP1sjIb3Ztd1TE/eBI9CIaBO3O5pjR9ppeXdCMPOXM6gEmS/v8TYOikFAow2Wz4m5TOGj+Lk+dSQG9325KEv9ewD4Vlj6+k="
    ports:
      - '4102:4096'
      - '4103:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.9
