version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node1.json" --publicIP $$(./getIP.sh node1) --ormConfig "config/e2e/network-stuck/ormconfig.node1.json"'
    environment:
      - NODE_ENV=production
    ports:
      - '4096:4096'
      - '4097:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node2.json" --publicIP $$(./getIP.sh node2) --ormConfig "config/e2e/network-stuck/ormconfig.node2.json" --peers "/ip4/$$(./getIP.sh node1)/tcp/4097/ipfs/QmNurLAfquUV58wu5JqfVk6DnRACpkzaurNzm9WK4ARfYd"'
    environment:
      - NODE_ENV=production
    ports:
      - '4098:4096'
      - '4099:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.5

  db3:
    image: "postgres:9.6.12"
    container_name: 'db3'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.6
  node3:
    build: ../../..
    container_name: 'node3'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node3.json" --publicIP $$(./getIP.sh node3) --ormConfig "config/e2e/network-stuck/ormconfig.node3.json" --peers "/ip4/$$(./getIP.sh node1)/tcp/4097/ipfs/QmNurLAfquUV58wu5JqfVk6DnRACpkzaurNzm9WK4ARfYd"'
    environment:
      - NODE_ENV=production
    ports:
      - '4100:4096'
      - '4101:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.7

  db4:
    image: "postgres:9.6.12"
    container_name: 'db4'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.8
  node4:
    build: ../../..
    container_name: 'node4'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node packages/main/dist/src/app --config "config/e2e/network-stuck/node4.json" --publicIP $$(./getIP.sh node4) --ormConfig "config/e2e/network-stuck/ormconfig.node4.json" --peers "/ip4/$$(./getIP.sh node1)/tcp/4097/ipfs/QmNurLAfquUV58wu5JqfVk6DnRACpkzaurNzm9WK4ARfYd"'
    environment:
      - NODE_ENV=production
    ports:
      - '4102:4096'
      - '4103:4097'
    networks:
      my_net:
        ipv4_address: 172.20.0.9
