version: '3.3'
services:
  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    ports:
      - '3000:5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/68-secrets/node1.json" --publicIP $$(./getIP.sh node1) --ormConfig "config/e2e/68-secrets/ormconfig.node1.json"'
    environment:
      NODE_ENV: production
    ports:
      - '4096:4096'
      - '4097:4097'

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    ports:
      - '3001:5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 15s; node packages/main/dist/src/app --config "config/e2e/68-secrets/node2.json" --publicIP $$(./getIP.sh node2) --ormConfig "config/e2e/68-secrets/ormconfig.node2.json" --peers "/ip4/$$(./getIP.sh node1)/tcp/4097/ipfs/QmTEfBHjNABsYevH1vXusACzwv9GSBrspc1rqvbkMXv8sN"'
    environment:
      NODE_ENV: production
    ports:
      - '4098:4096'
      - '4099:4097'
