version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:
  jaeger.local:
    hostname: jaeger.local
    container_name: jaeger.local
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_DISABLED=true
    ports:
      - '16686:16686'
      - '14268:14268'
    command: [
      "--query.max-clock-skew-adjustment=1s"
    ]
    networks:
      my_net:
        ipv4_address: 172.20.0.22


  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 15s; node --experimental-vm-modules --no-warnings packages/main/dist/app --config "config/e2e/68-secrets/node1.json"'
    environment:
      - NODE_ENV=production
      - GNY_NETWORK=localnet
      - GNY_PUBLIC_IP=172.20.0.3
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db1
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASpgkwggSiAgEAAoIBAQCjOzxR7ejzkXo1wnQaq9vP8y4xZt/81r0iFgpm7OPtrNGTtZNkU/18hpjRyUHzFnIxaDHmCZqxutMun5x/1QG+UenuOAeeO+k6HnqBf0bqK3TEA1klvQGyTZxj90aWO11S163gnyIpA8XxfS2FQo6odF1gqrs0E0hSy0mQepXNgzqzgqh8dhwxPGtHib/nLNdUaoqx9JYHdOdBalG27VWqiGdRZiXuA3x2lPbxkVjjECK6pKjbX3qYDpAssCUZG15Bk5Yx1H0KKp+A/jBHyI3BZyEd+1uO59URwDmzyi2MRdguBou146zCLx3d9ZkKCSJQ39v3XtAOC/jyg5htAu2tAgMBAAECggEAVx+y3ngBsp+ffzo/Bk1cke3WZf/m5ekoIh1ph+5A6gcoBZMRDKfX0LN2teKaFMmSQdS/bW0K6HozZdtDiOeEerT2C3RUfJy1q5PBB4WLsElplYXD+2SalzTdmG3PezhMY39DC3VkokelS3Po7AvOYRNbE9GNAgqYu7hNl5QWiQ37+f4LsMn6OvNHZRZpARED2LhGj1xMp6EVgEMQvtpDQ4GyUfdEliACRcmHkeisL0jgYLpRHNx5ekl+IDvnIhaf4Svi3vCEpDPcLeZG6gPCv74cxVRtN7NhuI8S4b4eTgNnI19XL10QabI3oISxke98+yCdkQhOAqfRE4qSjRQpAQKBgQDNq+FFaa7PVpVg3fi92G5oi7tkPb9nIMs584vCK5qWO8ILC5G/WLt1kVu3u7CqjJ9+8sJoUHWa8P8ZGVqXJdd4dssp+njJET2rRi6+KMUsfRwCWayoV9IF4BkBRsKi71zlG3bqO3tog4mDlkjh4a4TxBxqwmT9BvEPMrlAEXDh8QKBgQDLLLwhiaXCcMIDlsCIkyoB7lRZEjUJZtchinZPIK+PSyQ6dsOULn8WkrO4ByAhpdKuMMgY2nBmNFB6uNzzZh9+7NwBsn0UCz9T8UGjH5u+ru6NbReACyQGqxrMOUQUWHSE1gio1dtnAHqtbzEqGM2zhKwTmzc/dz1tzu11XuNLfQKBgB5OWnZ4+SpSLtbEPpfy4WoEVQuTUbXnjiqu6YQmGrRSf+hSvxo7//t1/NbZEFJBQGtbaCwo1vuK0XwoUUH+cH6uuocoAk5WfQjU4aRhq5Q/pzXtctSnhCobeHPIsnuB2+Vio6YmN6wR3dyG85xdPeJpvmo41Nq4ACNmLQf0yfZxAoGADzM2k++/Ve+npCsYFl+kKebRqqRBEYX/HERGm57fY4IEoNcXxLNB0MeC6Ian8bx9KYj+v1VASXUqfDPuW8tNGerQftQCpYg94aLP/Us1FKvzruL1eh/bPyB37cVvAXKorPNyTGdLdcZEZ0tFS1f1s7N+SC05keby0o9Dlp9Vs+UCgYBEhKHL1qxjGuuQTFAen8Mu7F1wFA6z/qR+giaNMhA6hWL+xyNowm8mgGR20DT4GCcM8/ABo0y+GlKQTi3wCLbroHG3BU3g/oxxw1tIAue2oawEpkb1NnuBWunSslBJRHTOIwvNjg7H64OATw8LaRTOjergD4coyHOY9S2dh3RXtg=="
    ports:
      - '4096:4096'
      - '4097:4097'
    depends_on:
      - jaeger.local
      - db1
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose:
      - '5432' # only internal
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 20s; node --experimental-vm-modules --no-warnings packages/main/dist/app --config "config/e2e/68-secrets/node2.json"'
    environment:
      - NODE_ENV=production
      - GNY_NETWORK=localnet
      - GNY_PUBLIC_IP=172.20.0.5
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmTEfBHjNABsYevH1vXusACzwv9GSBrspc1rqvbkMXv8sN
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db2
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASpwkwggSjAgEAAoIBAQDPZqpB+rHgWRICMVS0R296QXjJmvkg4dlZvv3yYR7A2hfa7YgCRwzjZeFHi2aVGl9J/L/fnH1E28UOHAngPA8i+Ix14xIEuRs3+WGZGKyllgsiID9MAhTHgK7ktrVWp1e8yvu8wUIz1RammBBIH7xm0+otJRDCJJeapVyTTB+mfs31lzsYRMGDjQrMy/21ec7O4BMqLiaMYp1cZHmtf7tmyfVEbPhpM4irBKeVurwt9HYcO+i8jVj60jnCjfFcsPBvHnUEj06lNgE+/9J7S6Z7n7MTVuxCBCs4HPbbKHfolin1HOcYcje64K78qdlGnnurG23P52ie1OStvdBW6YFvAgMBAAECggEAOIh7kFCNe+HLjt1zgVCXinOeQRYFInltjZEKF69xeo/4QKzOjhBf6vwyVBYjeDEgGELU6lb1rndZV2c9Keo1Fgs5/khO+Qqb6L4JZHndVaV4k2zG1CkdEOR6x80l0OD8gXGy/NiQ+x/ydKauiXpdGIpbIsMftkvTJ0w718rANdmMsc0QWn1APatld1F/BStwNKVw2jB/KukzD4S7GEyEkXOH3h2G31yv0ljK+WpwGK4YhF5bwDRM/8VFjTPfpR8RfUUok1JrG5BOIRWjxJgw0Wfm+edOprHL0HMmyORIkFns63/9+2p636pp5+kPcfHiKBmj7lr4ku99DBQyekMrAQKBgQD58RNVkkwmznZQfcpdHDY0CU1EDCPxjhppp6CxOog7Bw7CqpXx8AMet3vkX7/Ah5qxJXKwPkESqkModdWyDcMqQ3GfXsvfic6R+/Ctp9UdmwBzJRLqT4RNaEIxIuP4xPXxlLqddJlm3NAg/rK6fYVLyvDCWIGzuMO7/VXeHhQx0QKBgQDUbZ5ZNJu0HdI9iX1aHJxgarHMfF9eN16WLMzNa91K+p0kXIrx4c7dEVU2DW77JYRI/6E1Tc2EvMAPFgOdEqT+vhhJbljzx2+M0fdXz4ImmssnJEmeAaBGVcYIYnhLe6MCwpA9GFGPfVgR6fmJedxAldKuGm/Phq6uFWO5nCYPPwKBgQCE2CZvl/eTtK7b70/slz8T/1Gq9kzwaZgOSgM1z6dywDiPLP3PfsMZw2o9IssXOLv2pbHEjQInOonBaofvQDNYNkqg61Cu+l7p5p+wnQC/4I+no6/fC+6E+gIcfa/vnDggc+2QHNYf/wM8VkOGrYp4k1/N3B7r+CtIssi96vzO0QKBgHIvqlqRKNEc5pIlgbgagQRi1cfxYuImKTXYRw502LMhG68b/6QdmTDDzGYNuoZNmFoU7vbUJ5EeVK7HSpH4H7C/RhbStgX0QkYT5zzQUkmmE2Wq39eLUDf+i0CejcMlZm5pX1c35z+WROz8NCJt2rLs1h64HzoST3tMDBsNkHfJAoGAMhqgJbfE2Sg17N/261KgX5oKtITN/qG3WgkQtOD6GZcj4hldZwoFuk31cq/41HI8fB5Wya2rDwxABxh3hU3Fi6Q2IOxvi1lCQ6NxjV63ec0bIsxozWfbEd5tJp12hAplKZJZUXIbA3b4/Q/+Rpg4fFWZb5fBRx4hQDUlJ4/7FRg="
    ports:
      - '4098:4096'
      - '4099:4097'
    depends_on:
      - jaeger.local
      - db2
    networks:
      my_net:
        ipv4_address: 172.20.0.5
