version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:
  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/fast-connect-to-network/node1.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.3
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db1
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqgkwggSmAgEAAoIBAQDTYWKkPRttl8bFamFMItJ1az61oIUOtxeKZihFXrxfaRB01RBT2bSEpE3mFQERuVoVhFhfkYqTSn/AvmvhutIGiHZYREgDmzedohOgoWEAy4B1a95I2P2xNql2Xr6o/38GIl+D28q6FNQw/Q+/yLP3K0D2jpcHb6m0KDdjR7HxNB8tlLWVDZg1ak+7YSM2mpfrtUvfdx7Dk2Y0g175HL9L/DvsUuIyDBRFU2b4RUPRYjR8fW8his+T5Z7kCal6rrzMbU5aYsnB1ZndZ77+sQG1Ge4MpfxLejmcySwDOYYjX65j89xFYRD6cBPBUA6A7ogCqAtOdD3NA+gNdZiSs8OlAgMBAAECggEBAIRZc3O2Nxg1ceVlqCoNm4yda5Q5P1ZpWTn0oL5ehL+QfxdH2INHynlKjuPCvvqj/T1/sf2UmRmECd1a3R1m5d3lT4QQrK5lXzs5oeRvZtcik/nxYipmguGUgiJ1TBdwcc4bc4aR9arxI7LQoC3KsrPNx00ZFoM3bSA6FgP5ffaxMWAdaNHSatfMsJuE1Ty9RYUTJ4c+zuxb+WxDlFiqY4E03c+6ebSOSIRnM8GA4DeMSfXqqaX87CShohRhGHqFPs1su7HwKzdFvqKn+lWCFUaIx+32gZwdva4M7d2ENHK/mr2wpI95XQIykLBk+8XnI4qnZ7QvUSQBuG4PLcCLuEECgYEA/olSguUfB/XME7tIX0MADdx16HA068pfXG3wP17BGCRAcWiV6Som6rL8ui5lDfFdjTRFoIV5GGCAhQx9eQafXeh7JcGyCnL85g9fHhu9VI0toZKBTmuFtptGfIOS2L89neWaj1HqNDsHzbxsZNtW+WXr5fIcyBFAF1y72qXOMnkCgYEA1JiJkC+ExoL5bfimtEuHdatS7KJdOWePj8to4imVCSSpavvE/9MaZaJC9acMG56u3IwN1erZKr6rccVCxD0fntuwUg4KsKm2vUKehsZASHizpe+UEXDo6LLPtZwcmhuGwr0KF5WPNxy3ZmeTWCBG9MdqF4nKaAzGkerpDr5b740CgYEArzNqffqjr2D6xaIloJyHjwLujb2eT6aOmRp7QcNA+hMJ4IXymfmPrADjgGuq1zwJ/sW6H1GAFs1l6S69tu5eB8+b5FM874BSnzB5ckn5uhcrD4m+Q3IzKYwbql0OWO7ZxLNj/b6OjMENEAngOlPXu/bxtuc99GAbU3lbPJbgJVECgYEAz5tSIvK0h6KZb9H1AXYMh1VR+nGn9gnywOpTtyACQVaC9018GJMPYRauqvOBOGuiuQ8v56maf0qJY+XNiJNkEJ7atZauy8w//txSsKxjVCJC1RV7k/ieCbesbN5RdBDTbdJrS5Kqs5ggZSlaUyHaCOm/6dKOTUPEmfQ7uUEdyHUCgYEAkAl0ECTrxFpxbCPB1PfmDIBf/JycIicdyni/Kv/tyo+D96NtvsckBY0Hz/sQl7bCN1rSXubucHlOLrMX0QvQY6v/qR9Amm/Egz7Dgc/AG5dijSAxf2gDSPaLR8rWVTHOEjDmErNpcj2CXhfXurMTClr+MknECZtjKfMvu9ZvU0c="
    ports:
      - '4096:4096'
      - '4097:4097'
    depends_on:
      - db1
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/fast-connect-to-network/node2.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.5
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/Qmbv6kQMLmVUkuwp91Q3E5FEryQMR1MV56vNozSkGbtn2B
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db2
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASpwkwggSjAgEAAoIBAQC1G0K2evFkQ1hOnizy0CVblzK6Ls0scbobN2OPxdiCPEanx3A3awuXA5k1c7WkXfJj2uXrP1eV4NzBhQIawf+8IaFSTmlux7QzAcdMgyzmrw2oKZe35mAIk19PohPDNJLI0qhCv625HFLGikQfTG+cvVo5VuVIfsIATFnDESiFJk+9rgB1YUkzD+SUFv57AMYq06MeVzh3f9FMMTH5iExqcwyRHcslbJhsx1er6UWngqrxs7gtG5x7UIj9/p/kOH9THEjmrlE3L3Oo2hLYrE/VStBt5mvCLZhe69yEs2u45L4R7icIHZ9fMrsTB6SK9OGbKuhKELAJFIwwSraOPGORAgMBAAECggEBAISnxyHqw83xFknfyoTAudxwz5NYnKilVPCCjcbN4Fzk0cwrZaLyIbcnx51DeBVBSz6hJDBAYWNDJfAKARSgbTXcXFHxZYDjfrat4tHEc6s1Jge7D4qAkG83o2StD1S4uZun0d+yjwk8GdWbiXJzhn2EpQXDBIcpcejOBCHB+7AquF8nrbqx6Dmb4JHJertDHbbQRSYK82igTQRkKbnXS5Oat+ODcpS5sxxg9MNyXe3qx4FhSCRGKqdeD158GDj+5t41AYrcJqmic3lsa0Ostt9iOcqoUJUsz2937UZw505CIi+ulvU0c3UaXNapsDfJh6s9AU0MHq65H86gAnSG2QECgYEA2haFJ4rcU3K564AFh65dchg5460Z8t+wRStHZJZw+6gRh6zrtuGc2Y5yEhb7dxJAH9BCCGfd2xszj2s8dYD5SGbavEsX7GJWwj4ypKOeCufiDnEMomKbtE+C4bCmEYwH/yRCSNaeMZmcIIAZ9l/013OEeRuyGrKcX25hr6oGNukCgYEA1Jb3+NY2s0NwZCHxstf/dEXkc31a6jtyV07VdkeW2WpE9XeqCWKHBvVDn+BG0PMHmMgwTBnk1HALRsTu4ic5f5f0VJILEcG/r8DgcjIcsnbinmFwaawJPNc0b6uCtYrytwaq9TuG2UDVEtX1xV5r1LcZ66PKx0f3Cpti7lYCLmkCgYBpB3N1CbD2F0hmnC8NmvGx4uzuMw1OJGA1z5QAY1tiNxzKJIMYfisVsz5Ia/0K6SUsrRVACxWTUdRQ+6oQRN7I+Y/aIqgQ1YNG5MFq/Mk+I1KA9fzJr4ehHLHBk1tHFBM90u6BOarR5FKGbGsUdj3qDN39nVL2/JHGe9hbyxxXEQKBgEoL54VBv73C0KPf+trLR0wNiBv93qvVVuc4KzvOhalmzWweaRhpvBRdW1eVe7UN4WiC2ee34S9pc1QMBhS5itp5Z/4I/FgL/yNNcB/2em5i4F5AHDKCXJlXcAkxWQ64vf+oD+Xo/PgxD8ZGxhsf3zkxKZMc8uVkmJSWOOhBBvN5AoGAVAQHwQLDrlykrin7upmDp5b8pOTlXSHR2uxUp4eqOIWYU7i499zZ20FzSaS3oTAjtKuDbMaUXuAGGdo+9f3y/bqD5ET5iraSpawJ4N89RZTC32cnVio7JvSxwuOuukSiwy10Ng2NYwAGDixxM50fTdswqGfPqf/DNXTtDk5yKUc="
    ports:
      - '4098:4096'
      - '4099:4097'
    depends_on:
      - db2
    networks:
      my_net:
        ipv4_address: 172.20.0.5

  db3:
    image: "postgres:9.6.12"
    container_name: 'db3'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.6
  node3:
    build: ../../..
    container_name: 'node3'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/fast-connect-to-network/node3.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.7
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/Qmbv6kQMLmVUkuwp91Q3E5FEryQMR1MV56vNozSkGbtn2B
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db3
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQDysODhYM1Dh8zWYfHpshlweu0ZyvwHAR7rVGyzWFePz387t6CSrt3Cq8CNPu8GlkNq6P5kBXBWBM2ei00rYAd88AVIjWAhzRYDcOO3rog1EuXD+P78K9x1aMNzvtvofEPxw76VhMbXBykHg1XXYjNxDRlouT/NjubbkFwVHoYibr/FAeeJWlBQs6oLlZz2KTqoT/7HcK2SEYqIoDBfExgE8FE1O7Q5EqKPyQQa0+E0LH5IuoGZa9NlFMbYTVH8xRxgQRlUKOueqW3m7mzmHYqQxjdZmKaPOb8RjZDzVpup1PcF1ux9QC2q2vzaekB3huLcyan25JCaaV8wwMwI68hDAgMBAAECggEBAOWQOqf2ETPXuQLxEwuj1Dx5it3jDBL0FHM2ILxkzC7Ub93lDJazokEKhdEVvrPUX2E5k6i5HFHBqV5XFl/5LhwYTmcak9xlSnVmy4BsL5tEjOKbHVcbhiXpOzi5SPrY0MxYBGcaeZvcwgrBSOm7kj1VzrsowBmJGwaFvxSbEvZtRJiRJI4wCXpIkZpmLSJu7OU0CwQ59iwIfMh/JsODpsocZazG/ubSr5be0ZxT8d3Qzzqxc3pZHvhr0gHydMLLnH3f+sf/JX1wmpYzEt/uzoPyQyG5hrkwuVPpZ9jmqViPeGjKfmF0N8l5vLNAEdpQxHu1pnEPp2rzEvm8DdYzvkECgYEA+siHVTbK5bwPLFF5By02JC43DaSR7IB7VPVtRL+6iSj0AVRmAI3sGlt01fFQgW26hPsfyVz4WqXOvsEZC++xF/4ySB0RHYCjCPOMECvnSu7Iee6SLZ8nhOx71SI6FhRCfT/ng03xGJL0qoqVbQBPuuCHHUCMJr+LU0wVJxUuZM8CgYEA971BmG/gsAOJpkAkSNcjdL8B+wvKQvoBFDyxa5hMlt0HlA+P6duCacV2/7MnRpgVe9lYlo5lSyaATEmIjh12eAmqrkuzJzsa4Hqtrlkkx1XfL1g1UPxDksM8ofCRfq7PBxG99WiVYQVTrhEjRushOZNLS6K6wuCr59SeZgIaqk0CgYEA6QJAm/BY/LOK9YaNiRl84IkAJfDulGucLAgNCn+J9b7TWBju3T0ATk0DdXTNdDRbxQr/MbzsFG1SdvI7L1f5l21bkp1PNbY7xSlkzfG86WaLZp8/upvRwDNpq1It3i3cyTsDBID6rfZ81agFxk0vx1aus4MxtR7reO2MCdAoVwkCgYBzMytsgiG+V3bLuynkQT54jFWUcrAUIwMbcPmjqcd7o75haDcorO1g1/T1BE7wMcpTtAbQw9hwcK/aSZtZUnQDb6NRt1vQk1h1KDbZSxSiKNlGv8LTLOsTNPxd5WsSuKEGjYaCtqY33m1CFTANS0tA5bButHYaJrVpcWJS1wmlRQKBgQDWotY2C7kfyaEWHYDqVYaU4wp3lcPqhUV8te47abyTw2AphoLO2dQlnOA/zj2AQhvr/jzb6nMA2qpOYe4nFokDFHcatbWmpaaZzQYlsYVph5tnrMmYgZuQWEFjXbJeM4BAa1IbjMQisALOpYbZE9bV0wPtI/dha9uDIOT1UW95Aw=="
    ports:
      - '4100:4096'
      - '4101:4097'
    depends_on:
      - db3
    networks:
      my_net:
        ipv4_address: 172.20.0.7

  db4:
    image: "postgres:9.6.12"
    container_name: 'db4'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.8
  node4:
    build: ../../..
    container_name: 'node4'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/fast-connect-to-network/node4.json"'
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.9
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/ipfs/Qmbv6kQMLmVUkuwp91Q3E5FEryQMR1MV56vNozSkGbtn2B
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db4
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqAkwggSkAgEAAoIBAQDsnOk56NYf/BBnyQ58aBTJEO4G4OD10jiPCo7qT8yVbx2VRA7+vzJvq3f7qpf8rvwTevf9xdmoRkVZICSimtFrXTG7v+oGvlQ+TVYqcY/fTqtXO+9+UO47BDQkOLItsZVNP3ThSYKItdQoWkqSdRefck3gI2cJyeq8HFujDwY5tvOzU1m9N6/a4fpWrqoQlergDTm4nIZiuXrD+xU9n4oPGRQtOH3i/RaYFMzJbbXYebl6H/DHiOWJ/HZt32nX6UvLheVV5ibLBRmPfHKQReat7Jcebq5r2HtuWkLK/eGEzI6bpDDFVobdxPt2KWSW8pEYpHPe4OJUQU4Xclu6nrR/AgMBAAECggEBAKFA7tHAlO2HY8bXhz/RzxiYqR+W8rmVY2ZY071sVQkiiQ7JK08CDuV7/nFNefeDadf83jXdONEt0uVCurT2vfJluRczW9Lss40iN68FZf/SJYN2HWoAzdr6qm5lFUl+1TmoHYfMCWISSVyW7GuT0V2hEOHIPti0+3zn9qvR+XQqo7NntEv5Ae9QA/5d3tRdCzbIn+6nibAKRcHiJf/7J/xA3jaVrFKRSDlW3MOuBjD+sr6fqnx0zC7yw0CbMxNjRGyIx0TI2hC3cKl7rBdY6EyVaUiecemeLwnxcSovIMfvkgZwYfw8X5srn+IysOGam5ljvZX/i0gEFDBCMAJ+ZwECgYEA+xNw5PwW49dQCEVSbi7fJSAe+bB2cI+kdmITaJ/H9evz1DMEnsNBaSgMN5kRGUOdgtRKxGOwZ6Cy3sX2wTk52Kt8UHiHrmdcIWSkxtHY43sglsMEOSyF+GkY2lFT7Ayl9f+ZdvH0bDDdCo+gk00HfBqJFGkebGlt4jT3D6reFfECgYEA8UDbTfy1DaDh2Whs5RF4mPmL5tnW/GyTrVQmQ9RDeNub81A/UXstvrWZNyy5LdnXeBiXFNfzZ3erJ+//1uTlgxVS4SIOjeK2Hxd3quazz/LYKi/PjOhKtoNlSydyac4UA6SaSmvPQmMb95uMmxC4ECezJ18IYT1pYlKC0MfRQW8CgYAYn0hz/FDWWTgtB3dU/N2/S04eWHLVCREs1uNmYD0A3fnUdohedXGFuXqxPR6TJrFcsir+5XPYRcck168iNdV5bR/M2HUd4l8Dm1YZdVzauilw/4D7hmVA/jWEu3MKdBcWb9GB+6pnrccPkRRDPcudHRESYliscw5mn6EW9T/AUQKBgFcsiVH/y2hWRuWpLxgCnSIhoeTTuDRUA3SxIHaH/61vJUXhLFAEA36S3f8q4OrpeUtDD2yPr7smaakvtrFu2mPoU59YEAxC7G4Fq88MN9MfO+7agdO3qC+VAQgMA/KpbV/3nWzg0e56I4PwJ/lsLCZiQgEq/LsuVqMZj31jhoBvAoGBANEa/s+3s6L4wXwFNWA6sNIZaO29AYm7kFDg6m6DkqktQjsjPYSMPt4aKjBhWs5JgbEw3YxJG4UbiFLafBnt9tciMZlBllakHQFUteg7qJVAuaDi/q/6+uMLRh6E6QlimZ7El4a/O9aKZp0ajgfU/sPKsWAxjgrgovyj4mWuNCbd"
    ports:
      - '4102:4096'
      - '4103:4097'
    depends_on:
      - db4
    networks:
      my_net:
        ipv4_address: 172.20.0.9

  db5:
    image: "postgres:9.6.12"
    container_name: 'db5'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.10
  node5:
    build: ../../..
    container_name: 'node5'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 10s; node packages/main/dist/src/app --config "config/e2e/fast-connect-to-network/node5.json"' # connect to node4
    environment:
      - NODE_ENV=production
      - GNY_PUBLIC_IP=172.20.0.11
      - GNY_P2P_PEERS=/ip4/172.20.0.9/tcp/4097/ipfs/QmQotptpNYLj5KwMUAmVTKS2QmcpHmtYRa3EmrGnGsJicU
      - GNY_MONGO_LOGGING_DISABLE=true
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db5
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqQkwggSlAgEAAoIBAQDTyY3in9FHjY9yI3SagHPvffAqkzEpIcSGiNfgCtxQg4bemR1GPg9TfBqyYwU9jN/dun0Ynkrr/YvFPLlY/4DudsBf/RrlDyMq92h9yCz//5V9bJHWARa5ZUjGYiJNGPsooeX+IqmrMpNw4CPhKIvp9Ffks1JONW5KcOOA/vr4nDfD6DCHRVuxxLuBB8PR6tWNatut4DU6wwGbzGSqD1J6Avjk2IftNZmXU4PQvFeLmO2dbXdntvheiMETP94Oidx3pOdWxwZ6Eu7lsKc0NUMduiL/YF5OfSCfSHwgV4aNX/FyDRW12J2KpY+XII1nlHnaiBlr2YWXHXpbg9D3i3//AgMBAAECggEBAKIt9FMY42ARzUkwUXiG6UD6hdF0ie7fhuknHXjZmECnl74aLkq992qM3LzCCx9JI51d07HodaMls8TEbYLzlb4GfeaDofbKkrmyX/gCNEONauJzI3JnvwkVwJb6Sx4TBTHmWIM19Au/XRzQ52jibdIoZK4ji+GMFPs4W19K4tFBGsLddIL8cRXfaXDwfNmj9vZYqNuMgeLDWDG8jqfSX7XgpBnSZLn+n2jUkweWJYOQtR96BNXgRkhoiLomDa5cnhiH3PgTs32RE89BBGx2Mv2OUKSuyS6zQo938CxpwN0E1w9TOJt264WrhrLizYLAzMoCdqQjhjM6TZl95yblGlECgYEA8AdaMGBgCvTtuo4Q1Qa3t3aNEOcmnXiVshmbuurqAp/OylY0VrM0qzk1nS5lg0LO0/fDSLXKCt9jQDIjvvOMQod+IFbNiD8h4x3TkMTIneJsWGSG7K8FuLIRqnhbHi4R/EDFDf33HoO2xOzz6VSEw3fCxxZGU0VxUg2aLs/MCpMCgYEA4eEjXJxgsDorY2ren1RPoRJjvSUwYM3FPA7U6f9KfZY8aj88fvGc/BT9FOZMmeZEY30V3QnSGHQ55DvNVPr3Aiqj2MhJ04NNQ/jPD7wzq3djJK8SoIOfbq/WCLHHwjUkFpKgvMAI4ZtBSJYmehMsCSFo+sRbshiJ1/6voalX3GUCgYA5ZCimZITSWdn1vz47EU4gKdJ09i//evOgEAtyV/T4B6n0K0R8boDrZ9Rv7sYK6pB1kko5Om5Cx0L9+H8fizBAQBFiPh8Ksr2xhlItzT+CsL7jK7YvJXIixUEAF6MBxlY6kGoNfGn3+9pZn6Z6ZeEQs7P40lSiWHpN+j6hbsIEzQKBgQCXK8szzwCy0Kt7JOoLbizA2wLfcsU29GAdOrvqQ05CUMrsPJgrSV7MIuviEeOQWFjK0MtSHKF8dkTMZ+2bAz9PNuRjUGCAa27Jn/pMSKO4DPXQdk8cGBsaxBmVxg2v/0rAxK9Iw6jt/K8rejoUF0KwdajBs6q+vcd7RFuc8S35NQKBgQCX0kVV/cmUjXCDKUcp/4TaMtawEnkHLJobBB1ii8z3cWTKoMDyA7WKCe5VJVQmeyE1suC2m8KS9PFpllQ4QbI8bfi7h3z74eQttvZB5jETB8/VkmAwOrS9CJja9h7cHgwtOfVgAZzqZk7b+scppK+/mIX++t1qaHpfnLihXx8XPA=="
    ports:
      - '4104:4096'
      - '4105:4097'
    depends_on:
      - db5
    networks:
      my_net:
        ipv4_address: 172.20.0.11
