// custom type guards
export * from './isConfig';
export * from './isBlockPropose';
export * from './isPeerNode';
export * from './isNewBlockMessage';
export * from './isTransaction';
export * from './isGenesisTransaction';
export * from './isUnconfirmedTransaction';
export * from './isNetworkType';
export * from './isCommonBlockParams';
export * from './isCommonBlockResult';
export * from './isHeightWrapper';
export * from './isBlocksWrapperParams';
export * from './isBlockAndVotes';
export * from './isBlockWithTransactions';
export * from './isManyVotes';
export * from './isBlockIdWrapper';
export * from './isP2PPeerIdAndMultiaddr';
