// custom type guards
export * from './isConfig.js';
export * from './isBlockPropose.js';
export * from './isPeerNode.js';
export * from './isNewBlockMessage.js';
export * from './isTransaction.js';
export * from './isGenesisTransaction.js';
export * from './isUnconfirmedTransaction.js';
export * from './isNetworkType.js';
export * from './isCommonBlockParams.js';
export * from './isCommonBlockResult.js';
export * from './isHeightWrapper.js';
export * from './isBlocksWrapperParams.js';
export * from './isBlockAndVotes.js';
export * from './isBlockWithTransactions.js';
export * from './isManyVotes.js';
export * from './isBlockIdWrapper.js';
export * from './isP2PPeerIdAndMultiaddr.js';
export * from './isSimplePeerInfoArray.js';
