// consensus
export const SET_PENDING_BLOCK = 'SET_PENDING_BLOCK';
export const ADD_PENDING_VOTES = 'ADD_PENDING_VOTES';
export const ADD_PENDING_VOTES_SIGNATURES = 'ADD_PENDING_VOTES_SIGNATURES';
export const RESET_CONSENSUS = 'RESET_CONSENSUS';
export const SET_VOTES_KEY_SET = 'SET_VOTES_KEY_SET';
