version: '3.3'

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:
  loki.local:
    container_name: loki.local
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      my_net:
        ipv4_address: 172.20.0.22

  jaeger.local:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger.local
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_DISABLED=true
    ports:
      - '16686:16686'
      - '14268:14268'
    command: [
      "--query.max-clock-skew-adjustment=1s"
    ]
    networks:
      my_net:
        ipv4_address: 172.20.0.20


  db1:
    image: "postgres:9.6.12"
    container_name: 'db1'
    restart: always
    expose: # only internal
      - '5432'
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  node1:
    build: ../../..
    container_name: 'node1'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 5s; node --experimental-vm-modules --no-warnings packages/main/dist/app --config="config/e2e/network-fork/node1.json"'
    environment:
      - NODE_ENV=production
      - GNY_NETWORK=localnet
      - GNY_LOKI_HOST=http://loki.local:3100
      - GNY_DISABLE_JAEGER=false
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_LOG_LEVEL=info
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db1
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASqAkwggSkAgEAAoIBAQD4XrVAH0VzCsIjTXbng4KrMSCGMb5vnDD+dMN6VCWKtrbdkzmsULT9pNq/l6ef5EhRPMl5d6BQmYgoVU/V10mW60BtRyqUU4gDT11AsHD7V7Eik8Ghj6TMpKcOhWDghUT/zrs74rV9EoLUD8RZUGgkrwPx7+R3OgQKJMEBAe3ZcMuGFe8TLqPlaw1r2mQf5G2P4pe+zxnGoCKjXkqZAb59XyTa6nCBV1yOZE+F7q1AIq15tRqtdKr4ryqRgmkkH1YhHT3Mg8nx57fxnjzKPpQE+Lguzqkuk23u9eSZFHbNdL0e1fMPofdn/1O4MCdlLfXnnFIMzsGtsASJo4rz5U9jAgMBAAECggEACpsMtVDAh/GRKa3AopEwjrvZzjEolx59zxfQUxRtx/cWZu7G+y81E1GrT5wbuc2nMuTcG5Y6n8Z2lHZUIub/CvU/uorb7BqHB9EnQ8BlCq6Lb1UM4ye9m0l6ormaUewO7rd2sk9zfYRBVunXchLnZ42bpwSd5mNxUbeREEhzTiIX3coOWR+gT/uNraVxUoe98z6qaoa1HADednV0kH2tgmOmvb2x1mPFov+vDjdwog2gconJEqU0hluh519goz7xNcpitYdvH+HxcEExt5cCmM4fN2o2tODttcnpAO/dPQwz/Q1dAg79XqqT7tDxRgtza0HbnSnJsLDVuT/hwwJ5gQKBgQD8iAJbjTDNCN4rdqkOD7rGdDN/T6yOlxaxKrRXjb3k+uP0F7gbcsBijjkK40Oh4JWbTzb2zw4VxRuf1Sck5VrdMvECrXqTh7CJrmObJrExUrvatqD9XX96MsymgM8YWq/LuuVrBJl5CqasfQazuDyO2wSqLWxm8NKG4QBIThiA4wKBgQD7yBDpLPx5FkjyIYxb90Zg5nqqAM06e7Gmlv8Fe02L1s8QQIbZsRbzhtcmRiOUc/j3/QHP2lmrPeYfS35BfVSw2PypoksP9yFs6Brv3zh6LVi30rOsuRk0NPI837RE+tj5JINwW4idUMXeT2+D9bFfHgoPbFwxcAWQ3H7xVYG/gQKBgQCxwEJ4kq9RAvbu/P0N6sB7Q/ujlz9MtsjAN+Ds59ZMQNUHUVLD70e/l4BLS6ClZuGnimCT5TZy2GUTYgPFkrMck+jVC6sGATKgFuIBqYB7yVJ1Jqu264L5TpyCbpRW/i5TZuBpLbmhW3/qVa7L/diSbVOhPYvaAZUOX33FZ0MUJQKBgHjYMn2oENmRP5uvTG3LhiT2GkPENLxwJ/j8GhSodLS8eg+j2NVdMNXbjyIYofUboJBuB9OaSlVtVSkKE+Qc4mwrCUHl2j8kbw+Va3Bb5ACICT/ZSlGJWbZ7/xQGjsBY4ZDa3Jct56kR3pZv6+cbInGzukJi0PENgi5gFjGAx9CBAoGBAIXVh5LL+jDZuRL7eD/+V5Mp17CRuHDtflNIlcqk1L7EsyKqpFQnzurXnT07Hj1c4LJY7E264AV8+UfuF1Yn5fVl+jr7xO+LiBRR+I7CRsp8Vq7UPDlGZ6ZACNhU4PyVDhOb709TfPHc3Vokrq/OUlCGQ1beBzEZGvtLfrE4W7cu"
    ports:
      - '4096:4096'
      - '4097:4097'
    depends_on:
      - loki.local
      - jaeger.local
      - db1
    networks:
      my_net:
        ipv4_address: 172.20.0.3

  db2:
    image: "postgres:9.6.12"
    container_name: 'db2'
    restart: always
    expose:
      - '5432' # only internal
    environment:
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
    networks:
      my_net:
        ipv4_address: 172.20.0.4
  node2:
    build: ../../..
    container_name: 'node2'
    image: gny-experiment:integration # tags
    command: bash -c 'sleep 5s; node --experimental-vm-modules --no-warnings packages/main/dist/app --config="config/e2e/network-fork/node2.json"'
    environment:
      - NODE_ENV=production
      - GNY_NETWORK=localnet
      - GNY_PUBLIC_IP=172.20.0.5
      - GNY_LOKI_HOST=http://loki.local:3100
      - GNY_P2P_PEERS=/ip4/172.20.0.3/tcp/4097/p2p/QmPBzc5gBevMgM3wUUKqXgL3w4o2ntdzLFsUjrzHakEqhr
      - GNY_DISABLE_JAEGER=false
      - GNY_JAEGER_HOST=http://jaeger.local:14268/api/traces
      - GNY_LOG_LEVEL=info
      - GNY_DB_PASSWORD=docker
      - GNY_DB_DATABASE=postgres
      - GNY_DB_USER=postgres
      - GNY_DB_HOST=db2
      - GNY_DB_PORT=5432
      - GNY_P2P_SECRET="CAASpwkwggSjAgEAAoIBAQDE2Lwbi2HZLoESW3Sp7eV6E/F3YVvRt9X3Qv7fwyDPsJ7QKVMr+D3TGzL9tk9f2uNA5X2sit1nxKiEcpkE5I0E4/kuw8kYDrj0NWe2n5i+1LEmRmdEhACa0QFiMRuCdAHOS6w3F2kk9HK2L/ScCiDgtIXUPRkizlIpzKVkY8i6NKB9TmwfA0xIwO0pXL/xIcSGF5s65ugP4DdR/OyqmCUUOLDzJwHAisLRMkVTaT1n/lp6KFtW+BKnR50XyQ8KOVXh74KTVLRPNzmzVqUJnrn5NSWACML8VetV+HOZA2AgZuC8A2709NEIfUiNO4NnsUqT7gx1Q9401Ay7D3aeoKWVAgMBAAECggEAFlhiFiBe5agFR9+w4R9bxt1fskUPhsF/HPfyddUxMtJiXM/sHJgr8Hxsb+eToBZ5aKMEfqMu2fo1hP97RlZpea4lWb0o5T26miI72TvJu5PqXiVs0JbJeMmUBiD79fWUROZLMN/L9EF5ihvsgRAXRlrHvF2JLm3MXulXtwsqvJRMsBQJ1IpbkNha2giDthZqEZwAT1EiFjBsPWNeViPA5de+Q/e+x14pdj6gBeJpPEVFXtfiqh6Y3QpX+bM4q1/gTIZR1mgSQgn1Xpxz446YhVjX9YmIr5dtUZrh3YHeZyPOKu8vcQpdziwLXg/mXCBQBG7xywOSK+7o1VlETlH92wKBgQDxXfcqdoBFGibcelaZXVhFzaRrdOPAPiyMz9F26419Y1wqPHQuznfT2cNtRxabVMK6YJslVuTXwkGn5BCEwuSfVtzpJDzzXYJ9ng0tGldh4CDU6n27Gp5Tvgdf8wcZ8QpOruVXnJnO0zupORRFjAfyB9nqlKeb5XZ2oH+ppwGy9wKBgQDQx88UFAoavNeRYmVBCSiMvfzZqpsieW//2qLxsa/lHGzTHafWpBEDJtklsi+HpCvlDiuEoQpV3jhRUYxg08/Yt3nR016MaYAJm8nFA8nCQfJtPD87qnMIEIK40xcQ7w7BwPQ8DcbFjrZyMfTz6HlAbxJRZnk46msZxKsrUan80wKBgAmnJWRoWtbopdc5eU8m4YnhIIs/oIAmvGdhRFJKN11lZOE3i7n3felWEy/CoQ/TQvprNKk4oWxTk4agY1y74qLQuYMFdP6Spc5aTNKZ9Baw/P8m5aJe/SgCOI9Iy+bose3VpsxrMeeIoSEybDIf2I2AbOGp0k40zhkOcCybxkCfAoGBAMVC1EwTNwzWOhMaVbLiFVcNNvbt9A/Zj1G9YNFd4mRlvAiob2kksRI6RVcRiUjue666+bEheyNwh+OFWk4uMqZ/jHEM9btS/u+VK0mjb6DEMGq3TsNwI6mN+ATrJVMRm+7DAcAwAAuu8IDq5JcDonSXvUX9vTFig3jgUh3m1eaTAoGAFAv4qFvev7F7vrpbDKgc1/8KRfEw0QzT8jKiheW03DaidYkPge1peX10voIHJntGtZPRI4SynAHF40bK/GDklSCnMEWy+5jmRXSqYtjSqJmn0KC6f4+WNteTgI7Pck3CoDGvVifWlSXjALprE4NlBnkStMRkypk8e8+UOl+dy2o="
    ports:
      - '4098:4096'
      - '4099:4097'
    depends_on:
      - loki.local
      - jaeger.local
      - db2
    networks:
      my_net:
        ipv4_address: 172.20.0.5
