name: client integration test
on: push
jobs:
  orm-tests:
    runs-on: first-runner

jobs:
  client-intg-tests:
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: npm run test:integration:client
