name: client integration test
on: [push]
jobs:
  orm-tests:
    runs-on: first-runner
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '10.16.2'

    - name: restore lerna
      uses: actions/cache@v2
      id: cache-node-modules
      with:
        key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
        path: |
          node_modules

    - name: Build docker image
      run: docker-compose --file config/integration/docker-compose.integration.yml build

    - name: npm ci
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Run integration tests
      run: npm run test:integration:client
