on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop branch
        uses: actions/checkout@master
      - name: repo-sync
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        uses: gnyio/github-sync-ssh@v5
        with:
          source_repo: 'git@github.com:GNYIO/gny-experiment.git'
          source_branch: 'develop'
          destination_branch: 'master'
