name: Push to repo copy
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        branch: develop
        repository: GNYIO/gny
