name: e2e-test-1st
on: [push]
jobs:
  e2e-test-1st:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12.22.6'

    - name: npm ci
      run: npm ci

    - name: Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build docker image
      run: docker-compose --file config/integration/docker-compose.integration.yml build

    - name: Run integration tests
      run: npm run test:e2e:1st
