name: new release on testnet
on:
  workflow_dispatch:
    inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'

jobs:
  new-release-on-testnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout testnet branch
        uses: actions/checkout@v2
        with:
          ref: testnet
      - name: install lerna
        run: npm ci && npm run lerna:clean && npm run lerna:bootstrap && npm run lerna:removeArtifacts && npm run lerna:tsc
      - name: set github username
        run: git config user.name "$RELEASE_GITHUB_USERNAME"
      - name: set github email
        run: git config user.email "$RELEASE_GITHUB_EMAIL"
      - name: set github token
        run: git remote set-url origin https://a1300:$RELEASE_GITHUB_TOKEN@github.com/gnyio/gny-experiment.git
      - name: publish github release
        run: node_modules/lerna/cli.js version patch --yes --exact
      - name: build gny client
        run: node_modules/lerna/cli.js run --scope="@gny/client" web
      - name: set npm token
        run: npm set unsafe-perm true -g && npm set //registry.npmjs.org/:_authToken $NPM_TOKEN -g
      - name: set username
        run: npm set username $NPM_USERNAME -g
      - name: set npm email
        run: npm set email $NPM_EMAIL -g
      - name: release new version to github
        run: node_modules/lerna/cli.js version patch --yes --exact
      - name: publish individual lerna packages
        run: |
          cd packages/client && npm publish --access=public; cd ../..
          echo $(pwd)
          cd packages/web-base && npm publish --access=public; cd ../..
          cd packages/web-ed && npm publish --access=public; cd ../..
          cd packages/interfaces && npm publish --access=public; cd ../..
          cd packages/utils && npm publish --access=public; cd ../..
          cd packages/network && npm publish --access=public; cd ../..
          cd packages/cli && npm publish --access=public; cd ../..
          cd packages/base && npm publish --access=public; cd ../..
          cd packages/ed && npm publish --access=public; cd ../..
          cd packages/extended-joi && npm publish --access=public; cd ../..
          cd packages/logger && npm publish --access=public; cd ../..
          cd packages/type-validation && npm publish --access=public; cd ../..
