name: Publish last version tag of testnet branch to DockerHub
on:
  workflow_dispatch:
    inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout testnet branch
      uses: actions/checkout@v2
      with:
        ref: testnet
    - name: revert git to latest version
      run: git reset --hard $(git describe --abbrev=0 --tags)
    - name: getversion
      id: getversion
      run: echo -n -e "latestversion=$(cat lerna.json | grep version | head -1 | awk -F':' '{ print $2 }'   | sed 's/[",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push testnet (amd64) image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "gnyio/node:testnet,gnyio/node:${{ env.latestversion }}-testnet"
        platforms: linux/amd64
    - name: Build and push testnet (ARM) image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "gnyio/node:testnet-arm,gnyio/node:${{ env.latestversion }}-arm-testnet"
        platforms: linux/arm64


# check if variable is
# curl --silent -f -lSL https://index.docker.io/v1/repositories/gnyio/node/tags/1.0.69-testnet > /dev/null
