name: Publish last version tag of testnet branch to DockerHub
on:
  workflow_dispatch:
    inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout testnet branch
      uses: actions/checkout@v2
      with:
        ref: testnet
    - name: revert git to latest version
      run: git reset --hard $(git describe --abbrev=0 --tags)
    - name: getversion
      id: getversion
      run: echo -n -e "latestversion=$(cat lerna.json | grep version | head -1 | awk -F':' '{ print $2 }'   | sed 's/[",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gnyio/node
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        tags: "testnet,${{ env.latestversion }}-testnet"
        platforms: linux/amd64,linux/arm64

# check if variable is
# curl --silent -f -lSL https://index.docker.io/v1/repositories/gnyio/node/tags/1.0.69-testnet > /dev/null
