name: Publish latest tag of mainnet to docker
on:
  workflow_dispatch:
    inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout mainnet branch
      uses: actions/checkout@v2
      with:
        ref: mainnet
    - name: revert git to latest version
      run: git reset --hard $(git describe --abbrev=0 --tags)
    - name: getversion
      id: getversion
      run: echo -n -e "latestversion=$(cat lerna.json | grep version | head -1 | awk -F':' '{ print $2 }'   | sed 's/[",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push mainnet (amd64) image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "gnyio/node:mainnet,gnyio/node:${{ env.latestversion }}-mainnet"
        platforms: linux/amd64
