name: Publish develop branch to DockerHub
on:
  release:
      types: [published]
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v2
      with:
        ref: develop
    - id: myrelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: a1300/testnet
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        snapshot: true
        tags: "latest,develop,${{ steps.myrelease.outputs.release }}"
